default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --workspace --all-targets
        language: system
        pass_filenames: false
      - id: cargo-machete
        name: cargo machete
        entry: cargo machete --with-metadata --skip-target-dir kaos kosong kimi-agent
        language: system
        pass_filenames: false
